"""
Deterministic Safety Validation Layer for Voyager NL-Drone-Agent.

Every tool call generated by the LLM MUST pass through this bounds-checker BEFORE
dispatch to the MuJoCo simulator/controller. The LLM proposes; this layer disposes.

If a command violates any safety boundary, a SafetyViolation exception is raised with
an explicit, human-readable explanation that gets fed back to the dialogue node.
"""
import numpy as np

# ---- Deterministic Safety Bounds ----
MAX_ALTITUDE = 50.0      # meters
MIN_ALTITUDE = 0.15      # meters (ground clearance)
MAX_VELOCITY = 8.0        # m/s
GEOFENCE_RADIUS = 100.0   # meters


class SafetyViolation(Exception):
    """Raised when a proposed tool call violates deterministic physical/operational safety bounds."""
    pass


def validate_takeoff(altitude_m: float) -> float:
    """Validate requested takeoff altitude."""
    altitude_m = float(altitude_m)
    if not (MIN_ALTITUDE <= altitude_m <= MAX_ALTITUDE):
        raise SafetyViolation(
            f"Requested takeoff altitude {altitude_m:.2f}m is outside safe bounds "
            f"[{MIN_ALTITUDE:.2f}m, {MAX_ALTITUDE:.2f}m]."
        )
    return altitude_m


def validate_goto(x: float, y: float, z: float, yaw_deg: float = 0.0) -> tuple[float, float, float, float]:
    """Validate target waypoint (x, y, z, yaw_deg)."""
    x, y, z, yaw_deg = float(x), float(y), float(z), float(yaw_deg)
    if not (MIN_ALTITUDE <= z <= MAX_ALTITUDE):
        raise SafetyViolation(
            f"Target altitude {z:.2f}m is outside safe bounds [{MIN_ALTITUDE:.2f}m, {MAX_ALTITUDE:.2f}m]."
        )
    dist_xy = np.hypot(x, y)
    if dist_xy > GEOFENCE_RADIUS:
        raise SafetyViolation(
            f"Target horizontal position ({x:.2f}, {y:.2f}) at distance {dist_xy:.2f}m "
            f"exceeds maximum geofence radius {GEOFENCE_RADIUS:.2f}m."
        )
    return x, y, z, yaw_deg


def validate_set_velocity(vx: float, vy: float, vz: float) -> tuple[float, float, float]:
    """Validate requested 3D velocity vector (vx, vy, vz)."""
    vx, vy, vz = float(vx), float(vy), float(vz)
    v_mag = np.sqrt(vx**2 + vy**2 + vz**2)
    if v_mag > MAX_VELOCITY:
        raise SafetyViolation(
            f"Requested velocity magnitude {v_mag:.2f} m/s exceeds max safe velocity {MAX_VELOCITY:.2f} m/s."
        )
    return vx, vy, vz


def validate_land() -> None:
    """Validate landing action."""
    return None


def validate_hold() -> None:
    """Validate hold/hover action."""
    return None


def validate_get_status() -> None:
    """Validate telemetry status request."""
    return None


def validate_tool_call(tool_name: str, kwargs: dict) -> dict:
    """
    Central dispatcher that validates any tool call against deterministic safety rules.
    Returns sanitized kwargs on success or raises SafetyViolation on failure.
    """
    tool_name = tool_name.strip().lower()
    if tool_name == "takeoff":
        alt = kwargs.get("altitude_m", kwargs.get("alt", kwargs.get("z", 3.0)))
        validated_alt = validate_takeoff(alt)
        return {"altitude_m": validated_alt}
    
    elif tool_name == "goto":
        x = kwargs.get("x", 0.0)
        y = kwargs.get("y", 0.0)
        z = kwargs.get("z", kwargs.get("altitude_m", 3.0))
        yaw = kwargs.get("yaw_deg", kwargs.get("yaw", 0.0))
        vx, vy, vz, vyaw = validate_goto(x, y, z, yaw)
        return {"x": vx, "y": vy, "z": vz, "yaw_deg": vyaw}
    
    elif tool_name == "set_velocity":
        vx = kwargs.get("vx", 0.0)
        vy = kwargs.get("vy", 0.0)
        vz = kwargs.get("vz", 0.0)
        validated_v = validate_set_velocity(vx, vy, vz)
        return {"vx": validated_v[0], "vy": validated_v[1], "vz": validated_v[2]}
    
    elif tool_name == "land":
        validate_land()
        return {}
    
    elif tool_name == "hold":
        validate_hold()
        return {}
    
    elif tool_name == "get_status":
        validate_get_status()
        return {}
    
    else:
        raise SafetyViolation(f"Unknown or unsupported tool call: '{tool_name}'")
