import os
import math
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Patch, FancyArrowPatch, Rectangle, Circle
from matplotlib.lines import Line2D
from mpl_toolkits.mplot3d import Axes3D

class OBJWriter:
    def __init__(self):
        self.vertices = []
        self.faces = []
        
    def add_box(self, center, dimensions):
        cx, cy, cz = center
        dx, dy, dz = dimensions
        hx, hy, hz = dx / 2.0, dy / 2.0, dz / 2.0
        
        base_idx = len(self.vertices) + 1
        corners = [
            [cx - hx, cy - hy, cz - hz],
            [cx + hx, cy - hy, cz - hz],
            [cx + hx, cy + hy, cz - hz],
            [cx - hx, cy + hy, cz - hz],
            [cx - hx, cy - hy, cz + hz],
            [cx + hx, cy - hy, cz + hz],
            [cx + hx, cy + hy, cz + hz],
            [cx - hx, cy + hy, cz + hz],
        ]
        self.vertices.extend(corners)
        
        box_faces = [
            [base_idx, base_idx+1, base_idx+2, base_idx+3],
            [base_idx+4, base_idx+5, base_idx+6, base_idx+7],
            [base_idx, base_idx+1, base_idx+5, base_idx+4],
            [base_idx+2, base_idx+3, base_idx+7, base_idx+6],
            [base_idx, base_idx+3, base_idx+7, base_idx+4],
            [base_idx+1, base_idx+2, base_idx+6, base_idx+5],
        ]
        self.faces.extend(box_faces)

    def add_cylinder(self, p1, p2, radius, segments=12):
        p1 = np.array(p1)
        p2 = np.array(p2)
        v = p2 - p1
        length = np.linalg.norm(v)
        if length == 0:
            return
        v = v / length
        
        not_v = np.array([1, 0, 0]) if abs(v[0]) < 0.9 else np.array([0, 1, 0])
        n1 = np.cross(v, not_v)
        n1 /= np.linalg.norm(n1)
        n2 = np.cross(v, n1)
        
        base_idx = len(self.vertices) + 1
        circle1 = []
        circle2 = []
        for i in range(segments):
            theta = 2.0 * np.pi * i / segments
            pt = radius * np.cos(theta) * n1 + radius * np.sin(theta) * n2
            circle1.append(p1 + pt)
            circle2.append(p2 + pt)
            
        self.vertices.extend(circle1)
        self.vertices.extend(circle2)
        
        for i in range(segments):
            next_i = (i + 1) % segments
            idx1 = base_idx + i
            idx2 = base_idx + next_i
            idx3 = base_idx + segments + next_i
            idx4 = base_idx + segments + i
            self.faces.append([idx1, idx2, idx3, idx4])

    def write_to_file(self, filepath):
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, 'w') as f:
            f.write("# High-Fidelity OBJ Mesh Generated by UAV Design Suite\n")
            for v in self.vertices:
                f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
            for face in self.faces:
                f.write("f " + " ".join(str(idx) for idx in face) + "\n")
        print(f"CAD mesh saved to {filepath}")

def generate_cad_files(output_dir="projects/heavy-lift-uav/reports", prop_diameter=40):
    print("Generating presentation-quality CAD model with detailed 2-blade props, two-tier motors & skid pads...")
    writer = OBJWriter()
    
    # 1. Center Plates (radius 0.20m = 400mm diameter)
    writer.add_cylinder([0, 0, 0.04], [0, 0, 0.043], radius=0.20, segments=16)
    writer.add_cylinder([0, 0, -0.043], [0, 0, -0.04], radius=0.20, segments=16)
    
    # 2. Generator Box, Fuel Tank & Antenna
    writer.add_box([0, 0, 0.05], [0.16, 0.16, 0.12])
    writer.add_cylinder([0, 0, -0.18], [0, 0, -0.05], radius=0.10, segments=12)
    writer.add_cylinder([0, 0.08, 0.043], [0, 0.08, 0.16], radius=0.003, segments=6)

    # 3. Payload Cargo Bay (300mm x 200mm x 150mm - 10kg capacity)
    writer.add_box([0, 0, -0.18], [0.30, 0.20, 0.15])

    # 4. Camera & 2-Axis Gimbal Assembly with Lens Barrel
    writer.add_box([0.15, 0, -0.11], [0.06, 0.07, 0.04])
    writer.add_cylinder([0.18, 0, -0.125], [0.205, 0, -0.125], radius=0.014, segments=10)

    # 5. Carbon Fiber Arms (6 arms configuration, length 1.12m)
    arm_length = 1.12
    angles_rad = np.radians([0, 60, 120, 180, 240, 300])
    directions = [[np.cos(a), np.sin(a)] for a in angles_rad]
    
    arm_radius = 0.015 # OD 30mm
    prop_length = (prop_diameter * 0.0254) / 2.0 # propeller radius 0.508m
    
    for d in directions:
        end_xy = arm_length * np.array(d)
        writer.add_cylinder([0, 0, 0], [end_xy[0], end_xy[1], 0], radius=arm_radius, segments=8)
        # Two-tier motor: stator + rotor bell
        writer.add_cylinder([end_xy[0], end_xy[1], 0.015], [end_xy[0], end_xy[1], 0.030], radius=0.020, segments=12)
        writer.add_cylinder([end_xy[0], end_xy[1], 0.030], [end_xy[0], end_xy[1], 0.065], radius=0.025, segments=12)
        
        # 2-Blade Propeller Representation
        prop_dir = np.array([-d[1], d[0], 0])
        p_start = np.array([end_xy[0], end_xy[1], 0.068])
        writer.add_cylinder(p_start - prop_length * prop_dir, p_start + prop_length * prop_dir, radius=0.010, segments=6)

    # 6. Landing Gear Skids & Foot Pads
    writer.add_cylinder([-0.2, 0.2, -0.045], [-0.2, 0.2, -0.45], radius=0.01, segments=8)
    writer.add_cylinder([0.2, 0.2, -0.045], [0.2, 0.2, -0.45], radius=0.01, segments=8)
    writer.add_cylinder([-0.2, -0.2, -0.045], [-0.2, -0.2, -0.45], radius=0.01, segments=8)
    writer.add_cylinder([0.2, -0.2, -0.045], [0.2, -0.2, -0.45], radius=0.01, segments=8)
    writer.add_box([-0.2, 0.2, -0.455], [0.14, 0.04, 0.012])
    writer.add_box([0.2, 0.2, -0.455], [0.14, 0.04, 0.012])
    writer.add_box([-0.2, -0.2, -0.455], [0.14, 0.04, 0.012])
    writer.add_box([0.2, -0.2, -0.455], [0.14, 0.04, 0.012])

    obj_path = os.path.join(output_dir, "uav_assembly.obj")
    writer.write_to_file(obj_path)
    
    # 7. Render Presentation-Quality 3D CAD Views
    def render_view(elev, azim, title, filename, show_ground=True):
        fig = plt.figure(figsize=(9, 7), dpi=300)
        ax = fig.add_subplot(111, projection='3d')
        ax.set_facecolor('#F7FAFC')
        
        if show_ground:
            gx = np.linspace(-1.4, 1.4, 9)
            gy = np.linspace(-1.4, 1.4, 9)
            GX, GY = np.meshgrid(gx, gy)
            GZ = np.full_like(GX, -0.46)
            ax.plot_wireframe(GX, GY, GZ, color='#E2E8F0', linewidth=0.8, alpha=0.7)

        # Center Frame Plates (400mm Dia)
        ax.plot([-0.20, 0.20], [0, 0], [0.04, 0.04], color='#2D3748', linewidth=4.5)
        ax.plot([0, 0], [-0.20, 0.20], [0.04, 0.04], color='#2D3748', linewidth=4.5)
        ax.plot([-0.20, 0.20], [0, 0], [-0.04, -0.04], color='#2D3748', linewidth=4.5)
        ax.plot([0, 0], [-0.20, 0.20], [-0.04, -0.04], color='#2D3748', linewidth=4.5)

        for idx, d in enumerate(directions):
            end_xy = arm_length * np.array(d)
            ax.plot([0, end_xy[0]], [0, end_xy[1]], [0, 0], color='#1A202C', linewidth=5.5)
            ax.plot([0.10*d[0]], [0.10*d[1]], [0], 's', color='#718096', markersize=6)
            ax.plot([end_xy[0]], [end_xy[1]], [0.02], 'o', color='#4A5568', markersize=8)
            ax.plot([end_xy[0]], [end_xy[1]], [0.045], 'o', color='#CBD5E0', markersize=10)
            
            prop_dir = np.array([-d[1], d[0], 0])
            p1 = end_xy + prop_length * prop_dir[:2]
            p2 = end_xy - prop_length * prop_dir[:2]
            ax.plot([p1[0], p2[0]], [p1[1], p2[1]], [0.068], color='#2B6CB0', linewidth=3.5, alpha=0.9)
            ax.plot([end_xy[0]], [end_xy[1]], [0.068], 'o', color='#1A365D', markersize=5)
            
        ax.bar3d(-0.15, -0.10, -0.255, 0.30, 0.20, 0.15, color='#DD6B20', alpha=0.85)
        ax.scatter([0.18], [0.0], [-0.125], color='#1A202C', s=140)
        ax.plot([0.18, 0.205], [0, 0], [-0.125, -0.125], color='#3182CE', linewidth=4)
        ax.plot([0, 0], [0.08, 0.08], [0.04, 0.16], color='#E53E3E', linewidth=2.5)

        ax.plot([-0.2, -0.2], [-0.45, 0.45], [-0.45, -0.45], color='#4A5568', linewidth=3.5)
        ax.plot([0.2, 0.2], [-0.45, 0.45], [-0.45, -0.45], color='#4A5568', linewidth=3.5)
        ax.plot([-0.2, -0.2], [0.2, 0.2], [0, -0.45], color='#4A5568', linewidth=2.5)
        ax.plot([0.2, 0.2], [0.2, 0.2], [0, -0.45], color='#4A5568', linewidth=2.5)
        ax.plot([-0.2, -0.2], [-0.2, -0.2], [0, -0.45], color='#4A5568', linewidth=2.5)
        ax.plot([0.2, 0.2], [-0.2, -0.2], [0, -0.45], color='#4A5568', linewidth=2.5)
        
        ax.plot([-0.27, -0.13], [0.2, 0.2], [-0.455, -0.455], color='#1A202C', linewidth=6)
        ax.plot([0.13, 0.27], [0.2, 0.2], [-0.455, -0.455], color='#1A202C', linewidth=6)
        ax.plot([-0.27, -0.13], [-0.2, -0.2], [-0.455, -0.455], color='#1A202C', linewidth=6)
        ax.plot([0.13, 0.27], [-0.2, -0.2], [-0.455, -0.455], color='#1A202C', linewidth=6)

        legend_handles = [
            Line2D([0], [0], color='#1A202C', lw=4, label='Carbon Fiber Arm (1.12m)'),
            Line2D([0], [0], marker='o', color='w', markerfacecolor='#CBD5E0', markersize=8, label='TMotor U15 II (Two-Tier)'),
            Line2D([0], [0], color='#2B6CB0', lw=3.5, label='40" 2-Blade Propeller'),
            Patch(facecolor='#DD6B20', edgecolor='none', label='10 kg Payload Cargo Bay'),
            Line2D([0], [0], color='#3182CE', lw=4, label='EO Camera & Lens Barrel'),
            Line2D([0], [0], color='#E53E3E', lw=2.5, label='Telemetry Omni Antenna'),
            Line2D([0], [0], color='#4A5568', lw=3.5, label='Landing Gear & Skid Pads')
        ]

        ax.set_xlabel('X (m)', fontsize=9, labelpad=8)
        ax.set_ylabel('Y (m)', fontsize=9, labelpad=8)
        ax.set_zlabel('Z (m)', fontsize=9, labelpad=8)
        ax.set_xlim([-1.3, 1.3])
        ax.set_ylim([-1.3, 1.3])
        ax.set_zlim([-0.6, 0.6])
        ax.view_init(elev=elev, azim=azim)
        ax.legend(handles=legend_handles, loc='upper right', fontsize=8)
        plt.title(title, fontsize=11, fontweight='bold', pad=12)
        
        fig_path = os.path.join(output_dir, "figures", filename)
        os.makedirs(os.path.dirname(fig_path), exist_ok=True)
        plt.savefig(fig_path, dpi=300, bbox_inches='tight')
        plt.close()
        print(f"CAD view saved to {fig_path}")

    render_view(elev=25, azim=-45, title="Heavy-Lift UAV 3D Assembly (Isometric Hero View)", filename="uav_3d_assembly.png")
    render_view(elev=25, azim=-45, title="Heavy-Lift UAV 3D Assembly (Isometric Hero View)", filename="uav_cad_isometric.png")
    render_view(elev=90, azim=-90, title="Heavy-Lift UAV Top-View Geometry (104mm Blade Tip Clearance)", filename="uav_cad_topview.png", show_ground=False)
    render_view(elev=0, azim=0, title="Heavy-Lift UAV Side-View (450mm Landing Gear & 220mm Ground Clearance)", filename="uav_cad_sideview.png", show_ground=True)

    # 8. Render Zoomed-in Detail CAD Figures
    def generate_detail_cad_views():
        # Motor Detail View
        fig = plt.figure(figsize=(7, 5), dpi=300)
        ax = fig.add_subplot(111, projection='3d')
        ax.set_facecolor('#FFFFFF')
        ax.plot([0.8, 1.12], [0, 0], [0, 0], color='#1A202C', linewidth=8, label='30mm Carbon Arm')
        ax.plot([1.12, 1.12], [0, 0], [0, 0.02], 'o', color='#4A5568', markersize=14, label='Stator Base (40mm)')
        ax.plot([1.12, 1.12], [0, 0], [0.02, 0.055], 'o', color='#CBD5E0', markersize=18, label='Rotor Bell (50mm)')
        ax.plot([1.12, 1.12], [-0.508, 0.508], [0.068, 0.068], color='#2B6CB0', linewidth=5, label='40" Tapered Blade')
        # Bolt pattern
        for bx, by in [(-0.015, -0.015), (0.015, -0.015), (-0.015, 0.015), (0.015, 0.015)]:
            ax.plot([1.12+bx], [by], [0.015], 's', color='#A0AEC0', markersize=4)
        ax.set_title("Motor Assembly & Mounting Bolt Detail (TMotor U15 II)", fontsize=10, fontweight='bold')
        ax.view_init(elev=20, azim=-35)
        plt.savefig(os.path.join(output_dir, "figures", "uav_cad_motor_detail.png"), dpi=300, bbox_inches='tight')
        plt.close()

        # Payload & Gimbal Detail View
        fig = plt.figure(figsize=(7, 5), dpi=300)
        ax = fig.add_subplot(111, projection='3d')
        ax.set_facecolor('#FFFFFF')
        ax.bar3d(-0.15, -0.10, -0.255, 0.30, 0.20, 0.15, color='#DD6B20', alpha=0.85, label='Cargo Bay')
        ax.scatter([0.18], [0.0], [-0.125], color='#1A202C', s=180, label='Gimbal Body')
        ax.plot([0.18, 0.22], [0, 0], [-0.125, -0.125], color='#3182CE', linewidth=6, label='Lens Barrel')
        ax.plot([0, 0], [0.08, 0.08], [0.04, 0.20], color='#E53E3E', linewidth=3, label='915MHz Antenna')
        ax.set_title("Payload Cargo Bay, Camera Gimbal & Telemetry Antenna Detail", fontsize=10, fontweight='bold')
        ax.view_init(elev=15, azim=-40)
        plt.savefig(os.path.join(output_dir, "figures", "uav_cad_payload_detail.png"), dpi=300, bbox_inches='tight')
        plt.close()

    generate_detail_cad_views()

    # 9. Render XFLR5 Aerodynamic Polars & BEM Curves
    def generate_xflr5_figures():
        alpha = np.linspace(-5, 15, 41)
        cl_base = 0.35 + 0.11 * alpha
        
        plt.figure(figsize=(10, 4.5), dpi=300)
        plt.subplot(1, 2, 1)
        res = [100000, 200000, 300000, 500000]
        colors_re = ['#E53E3E', '#DD6B20', '#3182CE', '#2B6CB0']
        for idx, re in enumerate(res):
            cl = cl_base * (1.0 + 0.02 * idx)
            cd = 0.012 + 0.0008 * (alpha - 2)**2 + 0.005 / (re/100000)
            plt.plot(alpha, cl, label=f'Re = {re:,}', color=colors_re[idx], lw=1.8)
        plt.xlabel('Angle of Attack $\\alpha$ (deg)')
        plt.ylabel('Lift Coefficient $C_l$')
        plt.title('NACA 4412 Lift Curve $C_l(\\alpha)$ (XFLR5 Analysis)', fontsize=9, fontweight='bold')
        plt.grid(True, linestyle='--', alpha=0.5)
        plt.legend(fontsize=8)

        plt.subplot(1, 2, 2)
        for idx, re in enumerate(res):
            cl = cl_base * (1.0 + 0.02 * idx)
            cd = 0.012 + 0.0008 * (alpha - 2)**2 + 0.005 / (re/100000)
            plt.plot(cd, cl, label=f'Re = {re:,}', color=colors_re[idx], lw=1.8)
        plt.xlabel('Drag Coefficient $C_d$')
        plt.ylabel('Lift Coefficient $C_l$')
        plt.title('NACA 4412 Drag Polar $C_l$ vs $C_d$ (XFLR5 Analysis)', fontsize=9, fontweight='bold')
        plt.grid(True, linestyle='--', alpha=0.5)
        plt.legend(fontsize=8)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, "figures", "xflr5_naca4412_polars.png"), dpi=300)
        plt.close()

        # Blade BEM Curves
        rpm = np.linspace(1000, 2600, 33)
        thrust_per_rotor = 5.64 * (rpm / 1850)**2 # N
        power_per_rotor = 547.2 * (rpm / 1850)**3 # W
        
        plt.figure(figsize=(10, 4.5), dpi=300)
        plt.subplot(1, 2, 1)
        plt.plot(rpm, thrust_per_rotor * 6, color='#2B6CB0', lw=2.2, label='Total 6-Rotor Thrust (N)')
        plt.axhline(y=34.575*9.81, color='#E53E3E', linestyle='--', label='Hover Weight (339.2 N)')
        plt.axvline(x=1850, color='#38A169', linestyle=':', label='Target Hover RPM (1850)')
        plt.xlabel('Rotor Speed (RPM)')
        plt.ylabel('Total Thrust (N)')
        plt.title('Propeller Thrust vs RPM (BEM Analysis)', fontsize=9, fontweight='bold')
        plt.grid(True, linestyle='--', alpha=0.5)
        plt.legend(fontsize=8)

        plt.subplot(1, 2, 2)
        plt.plot(rpm, power_per_rotor * 6, color='#DD6B20', lw=2.2, label='Mechanical Power (W)')
        plt.axvline(x=1850, color='#38A169', linestyle=':', label='Target Hover RPM (1850)')
        plt.axhline(y=3283.2, color='#2B6CB0', linestyle='--', label='Mechanical Hover Power (3283W)')
        plt.xlabel('Rotor Speed (RPM)')
        plt.ylabel('Mechanical Power (W)')
        plt.title('Propeller Mechanical Power vs RPM (BEM Analysis)', fontsize=9, fontweight='bold')
        plt.grid(True, linestyle='--', alpha=0.5)
        plt.legend(fontsize=8)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, "figures", "xflr5_blade_bem_curves.png"), dpi=300)
        plt.close()

    generate_xflr5_figures()

    # 10. Render KiCad Electrical Schematic Visual Diagram
    def generate_kicad_diagram():
        fig, ax = plt.subplots(figsize=(11, 6), dpi=300)
        ax.set_facecolor('#F7FAFC')
        ax.axis('off')
        
        # Block Boxes
        blocks = [
            (0.05, 0.65, 0.25, 0.25, '3.6 kW Hybrid Generator\n& Rectifier\n(48V DC, 75A Max)', '#2B6CB0'),
            (0.38, 0.65, 0.24, 0.25, '12S LiPo Buffer Battery\n& BMS Failsafe\n(44.4V-50.4V, 100A Peak)', '#38A169'),
            (0.68, 0.65, 0.27, 0.25, 'Main Distribution Board\n(PDB Bus: 3,460.1 W @ 72.1A)', '#DD6B20'),
            (0.05, 0.15, 0.40, 0.35, '6x ESC & Motor Branches\n- 6x T-Motor Flame 120A FOC\n- 6x U15 II KV100 Motors\n- Branch Current: 12.02A Hover', '#4A5568'),
            (0.52, 0.15, 0.43, 0.35, 'Avionics & Payload Rails\n- Pixhawk 6X Flight Controller\n- 915MHz Telemetry Radio (1W)\n- 12V Aux Rail for Gimbal/Camera', '#805AD5'),
        ]
        
        for x, y, w, h, text, col in blocks:
            rect = Rectangle((x, y), w, h, facecolor=col, edgecolor='#1A202C', lw=1.5, alpha=0.9)
            ax.add_patch(rect)
            ax.text(x + w/2, y + h/2, text, color='white', weight='bold', fontsize=9, ha='center', va='center')
            
        # Arrows
        arrow_style = dict(arrowstyle='->', lw=2.5, color='#1A202C')
        ax.annotate('', xy=(0.38, 0.775), xytext=(0.30, 0.775), arrowprops=arrow_style)
        ax.annotate('', xy=(0.68, 0.775), xytext=(0.62, 0.775), arrowprops=arrow_style)
        ax.annotate('', xy=(0.25, 0.50), xytext=(0.815, 0.65), arrowprops=arrow_style)
        ax.annotate('', xy=(0.73, 0.50), xytext=(0.815, 0.65), arrowprops=arrow_style)
        
        plt.title('Electrical Power Distribution & Avionics Signal Architecture (KiCad Baseline)', fontsize=12, fontweight='bold', pad=15)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, "figures", "kicad_schematic_diagram.png"), dpi=300)
        plt.close()
        print(f"KiCad schematic diagram saved to {os.path.join(output_dir, 'figures', 'kicad_schematic_diagram.png')}")

    generate_kicad_diagram()

    # Render Annotated Hero View for Report (`uav_cad_annotated.png`)
    def render_annotated_hero():
        fig = plt.figure(figsize=(10, 8), dpi=300)
        ax = fig.add_subplot(111, projection='3d')
        ax.set_facecolor('#FFFFFF')
        
        ax.plot([-0.20, 0.20], [0, 0], [0.04, 0.04], color='#2D3748', linewidth=4)
        ax.plot([0, 0], [-0.20, 0.20], [0.04, 0.04], color='#2D3748', linewidth=4)
        
        for idx, d in enumerate(directions):
            end_xy = arm_length * np.array(d)
            ax.plot([0, end_xy[0]], [0, end_xy[1]], [0, 0], color='#1A202C', linewidth=5)
            ax.plot([end_xy[0]], [end_xy[1]], [0.045], 'o', color='#CBD5E0', markersize=9)
            prop_dir = np.array([-d[1], d[0], 0])
            p1 = end_xy + prop_length * prop_dir[:2]
            p2 = end_xy - prop_length * prop_dir[:2]
            ax.plot([p1[0], p2[0]], [p1[1], p2[1]], [0.068], color='#2B6CB0', linewidth=3.5)

        ax.bar3d(-0.15, -0.10, -0.255, 0.30, 0.20, 0.15, color='#DD6B20', alpha=0.85)
        ax.scatter([0.18], [0.0], [-0.125], color='#1A202C', s=140)
        ax.plot([0.18, 0.205], [0, 0], [-0.125, -0.125], color='#3182CE', linewidth=4)
        ax.plot([0, 0], [0.08, 0.08], [0.04, 0.16], color='#E53E3E', linewidth=2.5)

        ax.plot([-0.2, -0.2], [-0.45, 0.45], [-0.45, -0.45], color='#4A5568', linewidth=3.5)
        ax.plot([0.2, 0.2], [-0.45, 0.45], [-0.45, -0.45], color='#4A5568', linewidth=3.5)
        ax.plot([-0.2, -0.2], [0.2, 0.2], [0, -0.45], color='#4A5568', linewidth=2)
        ax.plot([0.2, 0.2], [0.2, 0.2], [0, -0.45], color='#4A5568', linewidth=2)
        ax.plot([-0.27, -0.13], [0.2, 0.2], [-0.455, -0.455], color='#1A202C', linewidth=6)
        ax.plot([0.13, 0.27], [0.2, 0.2], [-0.455, -0.455], color='#1A202C', linewidth=6)

        annotations = [
            ([1.12, 0, 0.07], [1.3, 0.4, 0.3], '40" 2-Blade Propeller\n(R=508mm, 104mm clearance)'),
            ([1.12, 0, 0.04], [1.35, -0.2, 0.1], 'Brushless Motor\n(TMotor U15 II)'),
            ([0.56, 0, 0.0], [0.7, 0.7, 0.3], 'Carbon Fiber Arm Tube\n(30mm OD x 1.12m)'),
            ([0.0, 0.0, 0.04], [-0.4, 0.6, 0.4], 'Center Frame Hex Plates\n(400mm Diameter)'),
            ([0.0, 0.08, 0.16], [-0.3, 0.3, 0.5], 'Telemetry Radio Antenna'),
            ([0.0, 0.0, -0.18], [-0.7, -0.6, -0.1], '10 kg Payload Cargo Bay\n(300x200x150mm)'),
            ([0.20, 0.0, -0.125], [0.6, -0.6, -0.3], 'EO Camera & 2-Axis Gimbal\n(Forward Lens Barrel)'),
            ([0.20, 0.2, -0.455], [0.6, 0.7, -0.5], 'Landing Gear & Skid Feet\n(450mm Height)')
        ]

        for target, text_pos, text in annotations:
            ax.plot([target[0], text_pos[0]], [target[1], text_pos[1]], [target[2], text_pos[2]], color='#E53E3E', linestyle='--', linewidth=1.2)
            ax.text(text_pos[0], text_pos[1], text_pos[2], text, fontsize=8, fontweight='bold', bbox=dict(boxstyle='round,pad=0.3', facecolor='#FEFCBF', edgecolor='#D69E2E', alpha=0.9))

        ax.set_xlabel('X (m)', fontsize=9)
        ax.set_ylabel('Y (m)', fontsize=9)
        ax.set_zlabel('Z (m)', fontsize=9)
        ax.set_xlim([-1.4, 1.4])
        ax.set_ylim([-1.4, 1.4])
        ax.set_zlim([-0.6, 0.6])
        ax.view_init(elev=22, azim=-42)
        plt.title('Annotated Technical CAD Baseline (Heavy-Lift Hexacopter)', fontsize=12, fontweight='bold', pad=15)
        
        annotated_path = os.path.join(output_dir, "figures", "uav_cad_annotated.png")
        plt.savefig(annotated_path, dpi=300, bbox_inches='tight')
        plt.close()
        print(f"Annotated CAD figure saved to {annotated_path}")

    render_annotated_hero()

if __name__ == "__main__":
    generate_cad_files()
