<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>px4_offboard</name>
  <version>0.1.0</version>
  <description>PX4 offboard control nodes for quadcopter autonomy project</description>
  <maintainer email="vaibhav@iitm.ac.in">Vaibhav</maintainer>
  <license>MIT</license>
  <depend>rclpy</depend>
  <depend>px4_msgs</depend>
  <buildtool_depend>ament_python</buildtool_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
